### ISSUE TITLE
Leaning subdocuments virtuals with select does not work on last mongoose version  

### ISSUE THREAD

**Issue by Fabiencdp** [mongoosejs/mongoose-lean-virtuals#50]
Hi ! 

With mongoose 5.12.2 and mongoose-lean-virtuals 0.7.6, just found that the next query only lean the root _id value :
 
```
 Project.find(match)
            .select('_id name')
            .populate('company', '_id name')
            .lean({ virtuals: ['id'] });  // we only need the id virtual

// Return : 
"{
  "_id": "5cade6a33c27940010c01de2",
  "company": {
    "_id": "5cadc7773c27940010c00298",
    "name": "SOME COMP"
  },
  "name": "A PROJECT",
  "id": "5cade6a33c27940010c01de2"
}"
```
result.company haven't any "id" property. 

From the past, with mongoose 5.9.1 and mongoose-lean-virtuals 0.5.0, the same query return : 
```
"{
  "_id": "5cade6a33c27940010c01de2",
  "company": {
    "_id": "5cadc7773c27940010c00298",
    "name": "SOME COMP",
    "id": "5cadc7773c27940010c00298" 
  },
  "name": "A PROJECT",
  "id": "5cade6a33c27940010c01de2"
}"
```
Virtual worked fine with subdocument. 

However, It work well using  `.lean({ virtuals: true });`. 
But we have some virtuals that we dont want to return everytime, and deleting them from each document/subdocument is not suitable.

Is it intended ?

**Comment by vkarpov15** [comment]
This behavior is by design. In order to get `company.id` to show up with lean-virtuals, you need to do `.lean({ virtuals: ['id', 'company.id'] })`
