### ISSUE TITLE
feature: support lean virtual methods

### ISSUE THREAD

**Issue by HsinHeng** [mongoosejs/mongoose-lean-virtuals#53]
[mongoose-lean-methods](https://github.com/teradonburi/mongoose-lean-methods#readme) seen to be deprecated.

could it support lean virtual method?

**Comment by vkarpov15** [comment]
We may need to write a separate plugin. Will consider this for a future release.

**Comment by HsinHeng** [comment]
> We may need to write a separate plugin. Will consider this for a future release.

OK.  Thanks for your reply.

**Comment by vkarpov15** [comment]
Closing this since we have a Mongoose issue open. Methods isn't something this plugin can reasonably support.
