### ISSUE TITLE
Dependabot alert: mpath < 0.8.4

### ISSUE THREAD

**Issue by rpenido** [mongoosejs/mongoose-lean-virtuals#54]
Issue solved in mongoose: https://github.com/Automattic/mongoose/issues/10683

**Comment by vkarpov15** [comment]
This should be fixed with Mongoose v5.13.9, so we can close this issue for now.

**Comment by vkarpov15** [comment]
Also, just to confirm, the security issue in mpath <= 0.8.3 does **not** impact mongoose.

**Comment by rpenido** [comment]
> This should be fixed with Mongoose v5.13.9, so we can close this issue for now.

I don't understand. This plugin is not necessary with mongoose v5.13.9?

**Comment by vkarpov15** [comment]
That's our mistake, we didn't realize that this project depended on mpath directly.

We can confirm that the security issue in mpath <= 0.8.3 does **not** affect this project.

We fixed this in d116890da2791784268e925eba9412837dceefb8 and released v0.8.1 :+1:
