### ISSUE TITLE
Not working with Typescript

### ISSUE THREAD

**Issue by SinBirb** [mongoosejs/mongoose-lean-virtuals#58]
When using with

`import mongooseLeanVirtuals from "mongoose-lean-virtuals";`

it gives the same error as the mongoose-lean-getters plugin: https://github.com/mongoosejs/mongoose-lean-getters/issues/11

    /usr/current/app/node_modules/mongoose/lib/schema.js:1406
        throw new Error('First param to `schema.plugin()` must be a function, '

Is there some other way to use this plugin?

**Comment by iammola** [comment]
I had this issue as well and solved it by adding this code into another types declaration file

```ts
declare module "mongoose-lean-virtuals" {
  import { Schema } from "mongoose";
  export default function mongooseLeanVirtuals(schema: Schema): void;
}
```

**Comment by MarcusElevait** [comment]
we use it like that:
```Typescript 
import * as leanVirtualsPlugin from 'mongoose-lean-virtuals';

Schema.plugin(leanVirtualsPlugin);
```

and it works
