### ISSUE TITLE
Chaining getter on virtual doesn't work with lean

### ISSUE THREAD

**Issue by MarcusElevait** [mongoosejs/mongoose-lean-virtuals#61]
We have the following virtual defined in our schema:

```Typescript
AnnotationTypeSchema.virtual('instances', {
    ref: AnnotationType.name,
    localField: 'classToAnnotate',
    foreignField: 'classToAnnotate',
    match: { textField: { $exists: true } },
}).get((instances: BaseAnnotationType[]) => instances.map(instance => instance.textField));
```

And we're trying to execute the following query:

```Typescript
const items = await this.annotationTypeModel
            .find(searchFilter)
            .limit(filter.limit)
            .skip(filter.limit * (filter.page - 1))
            .sort({ title: 1 })
            .populate('instances')
            .lean({ virtuals: true, getters: true })
            .exec();
```

But we get the error, that the instances is undefined and therefore the map function cannot be executed.

Don't know if the intended behavior of the Plugin should cover such cases.

**Comment by vkarpov15** [comment]
What error do you get? I notice you're using typescript, is this a compiler error or a runtime error?

**Comment by MarcusElevait** [comment]
it's a runtime error. as i wrote we get the error, that "instances" is undefined in the .get method body

**Comment by MarcusElevait** [comment]
So we had another point where we needed this and it seemed to work. Don't know if it's because of the justOne option, but it works i will close this issue.
