### ISSUE TITLE
How to add a virtual field to mongoose array of objects in a schema?

### ISSUE THREAD

**Issue by ajithv11** [mongoosejs/mongoose-lean-virtuals#69]
I have a mongoose schema as follow

    const mongoose = require("mongoose");
    const mongooseLeanVirtuals = require('mongoose-lean-virtuals');
    const ImageSchema = new mongoose.Schema({
      img: { type:String }
    });
    ImageSchema.virtual('img').get(function() {
      return `${this.img}/crop/720/720`;
    });
    ImageSchema.plugin(mongooseLeanVirtuals);

    const PostSchema = new mongoose.Schema(
      {
        title:{
            type: String,
            required: true,
            trim: true
        },
        author:{
          type: mongoose.Schema.Types.ObjectId,
          ref:'Customer'
        },
        images: [ImageSchema]
      },
      { timestamps: true }
    );
    module.exports = mongoose.model("Post", PostSchema);

Data result is 

    [
        {
            "_id": "64cb808d95a1ec6708a8e5e6",
            "title": "First Post",
            "author":{...},
            "images": [],
            "createdAt": "2023-08-03T10:33:31.253Z",
            "updatedAt": "2023-08-03T10:33:31.253Z",
            "__v": 0
        },
        {
            "_id": "64cb829a95a1ec6708a8f9ab",
            "title": "Next Post",
            "author":{...},
            "images": [
                {
                    "_id": "64cb829a95a1ec6708a8f9ac",
                    "img": "image001.png"
                },
                {
                    "_id": "64cb829a95a1ec6708a8f9ad",
                    "img": "image002.png"
                },
                {
                    "_id": "64cb829a95a1ec6708a8f9ae",
                    "img": "image003.png"
                }
            ],
            "createdAt": "2023-08-03T10:34:02.173Z",
            "updatedAt": "2023-08-03T10:34:02.173Z",
            "__v": 0
        }
    ]

In the database I already have a bunch of data, So I need to modify new image path in the return query as 
img : "image003.png/crop/720/720"

Is it possible to achive this using mongoose virtual ?

> await Post.find({}).lean({ virtuals: true }).lean().populate('author')

My expected result is

    [
        {
            "_id": "64cb808d95a1ec6708a8e5e6",
            "title": "First Post",
            "author":{...},
            "images": [],
            "createdAt": "2023-08-03T10:33:31.253Z",
            "updatedAt": "2023-08-03T10:33:31.253Z",
            "__v": 0
        },
        {
            "_id": "64cb829a95a1ec6708a8f9ab",
            "title": "Next Post",
            "author":{...},
            "images": [
                {
                    "_id": "64cb829a95a1ec6708a8f9ac",
                    "img": "image001.png/crop/720/720"
                },
                {
                    "_id": "64cb829a95a1ec6708a8f9ad",
                    "img": "image002.png/crop/720/720"
                },
                {
                    "_id": "64cb829a95a1ec6708a8f9ae",
                    "img": "image001.png/crop/720/720"
                }
            ],
            "createdAt": "2023-08-03T10:34:02.173Z",
            "updatedAt": "2023-08-03T10:34:02.173Z",
            "__v": 0
        }
    ]

**Comment by vkarpov15** [comment]
Yeah `await Post.find({}).lean({ virtuals: true })` should be all you need, `virtuals: true` should bubble down to any nested schemas. Here's a test case: https://github.com/mongoosejs/mongoose-lean-virtuals/blob/63f5c71e02376a7557698498d2d0679bebbdc75f/test/index.test.js#L258-L284
